{% set name = "langgraph-prebuilt" %}
{% set version = "0.6.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: e9e53b906ee5df46541d1dc5303239e815d3ec551e52bb03dd6463acc79ec28f
  # patches:
    # E   ModuleNotFoundError: No module named 'psycopg-pool'
    # E   ModuleNotFoundError: No module named 'langgraph-checkpoint-postgres'
    # E   ModuleNotFoundError: No module named 'langgraph-checkpoint-sqlite'
    # - patches/0001-removed-the-pool-and-unavailable-checkpointers.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<39]

requirements:
  host:
    - python
    - pip
    - hatchling
  run:
    - python
    - langchain-core >=0.3.67
    - langgraph-checkpoint >=2.1.0,<3.0.0
    - langgraph
    # https://github.com/langchain-ai/langgraph/issues/5086
    - langchain

# E   ModuleNotFoundError: No module named 'syrupy'
# {% set ignore_tests = " --ignore=tests/test_react_agent_graph.py" %}

# Temporarily comment out test section due to cycle dependency with langgraph.
# Package needs to be rebuilt with tests after langgraph release.
# test:
#   source_files:
#     - tests
#   imports:
#     - langgraph.prebuilt
#   commands:
#     - pip check
#     - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
#     - pytest -v {{ ignore_tests }} tests
#   requires:
#     - pip
#     - pytest
#     - pytest-asyncio
#     - pytest-mock
#     - psycopg

about:
  home: https://www.github.com/langchain-ai/langgraph
  summary: Library with high-level APIs for creating and executing LangGraph agents and tools.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: Library with high-level APIs for creating and executing LangGraph agents and tools.
  dev_url: https://github.com/langchain-ai/langgraph/tree/main/libs/prebuilt
  doc_url: https://github.com/langchain-ai/langgraph/blob/main/libs/prebuilt/README.md

extra:
  recipe-maintainers:
    - jan-janssen
